//! KAT-driven differential test of the verification path.
//!
//! The NIST KAT file `PQCsignKAT_353_SQIsign_lvl1.rsp` contains 100
//! `(pk, sk, msg, signed_message)` triples generated by the reference
//! implementation. Each `sm` is `signature || msg`. We parse the file,
//! decode `(sig, pk)`, and confirm [`protocols_verify`] returns `true`
//! for every entry.
//!
//! As a negative control, we flip a byte in each signature and confirm
//! [`protocols_verify`] returns `false`. The corrupted signatures
//! exercise the various rejection paths in `protocols_verify` (the
//! canonical-matrix check, ladder3pt failures, mismatched challenge,
//! and so on).

use std::fs;
use std::path::PathBuf;

use sqisign_verify::{
    protocols_verify, public_key_decode, signature_decode, PUBLICKEY_BYTES, SIGNATURE_BYTES,
};

struct KatEntry {
    count: u64,
    msg: Vec<u8>,
    pk: Vec<u8>,
    sig: Vec<u8>,
}

fn kat_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("vendor")
        .join("the-sqisign")
        .join("KAT")
        .join("PQCsignKAT_353_SQIsign_lvl1.rsp")
}

fn parse_kat(path: &PathBuf) -> Vec<KatEntry> {
    let raw = fs::read_to_string(path).expect("KAT file must be readable");
    let mut entries = Vec::new();
    let mut count: Option<u64> = None;
    let mut mlen: Option<usize> = None;
    let mut msg: Option<Vec<u8>> = None;
    let mut pk: Option<Vec<u8>> = None;
    let mut smlen: Option<usize> = None;

    for line in raw.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((k, v)) = line.split_once('=') else {
            continue;
        };
        let k = k.trim();
        let v = v.trim();
        match k {
            "count" => {
                count = Some(v.parse().expect("count int"));
            }
            "mlen" => {
                mlen = Some(v.parse().expect("mlen int"));
            }
            "msg" => {
                msg = Some(hex::decode(v).expect("msg hex"));
            }
            "pk" => {
                pk = Some(hex::decode(v).expect("pk hex"));
            }
            "smlen" => {
                smlen = Some(v.parse().expect("smlen int"));
            }
            "sm" => {
                // sm is the last field per record: emit on encounter.
                let sm = hex::decode(v).expect("sm hex");
                let count = count.expect("count present");
                let mlen = mlen.expect("mlen present");
                let smlen = smlen.expect("smlen present");
                let msg = msg.take().expect("msg present");
                let pk = pk.take().expect("pk present");
                assert_eq!(msg.len(), mlen, "msg/mlen mismatch in count {count}");
                assert_eq!(sm.len(), smlen, "sm/smlen mismatch in count {count}");
                assert_eq!(pk.len(), PUBLICKEY_BYTES, "pk length");
                // sm = signature || message
                assert!(
                    sm.len() >= SIGNATURE_BYTES,
                    "sm shorter than SIGNATURE_BYTES"
                );
                let sig_bytes = sm[..SIGNATURE_BYTES].to_vec();
                let trailing_msg = &sm[SIGNATURE_BYTES..];
                assert_eq!(
                    trailing_msg,
                    &msg[..],
                    "sm trailing bytes do not match msg in count {count}"
                );
                entries.push(KatEntry {
                    count,
                    msg,
                    pk,
                    sig: sig_bytes,
                });
            }
            _ => { /* sk, seed, etc. */ }
        }
    }
    entries
}

#[test]
fn kat_entries_all_verify() {
    let path = kat_path();
    let entries = parse_kat(&path);
    assert!(
        !entries.is_empty(),
        "KAT file must contain at least one entry"
    );
    assert_eq!(
        entries.len(),
        100,
        "lvl1 KAT file is expected to contain 100 entries"
    );

    let mut passed = 0;
    let mut failed = Vec::new();
    for e in &entries {
        let sig = signature_decode(&e.sig).expect("signature_decode");
        let pk = public_key_decode(&e.pk).expect("public_key_decode");
        if protocols_verify(&sig, &pk, &e.msg) {
            passed += 1;
        } else {
            failed.push(e.count);
        }
    }
    assert!(
        failed.is_empty(),
        "{} of {} KAT entries failed to verify: {:?}",
        failed.len(),
        entries.len(),
        failed
    );
    assert_eq!(passed, entries.len());
}

#[test]
fn kat_entries_reject_tampered_signature() {
    let path = kat_path();
    let entries = parse_kat(&path);

    // Pick a handful of entries; verifying 100 tampered signatures
    // through the full protocol takes too long for a CI run. The
    // first 5 records cover the common decode paths.
    let sample: Vec<&KatEntry> = entries.iter().take(5).collect();
    assert!(!sample.is_empty());

    for e in &sample {
        let mut bad = e.sig.clone();
        // Flip the high bit of E_aux_A's real-part low byte; that
        // perturbs the auxiliary curve so the recovered commitment
        // curve will not match and the final challenge equality will
        // fail.
        bad[0] ^= 0x80;
        let sig = signature_decode(&bad).expect("decode tampered sig");
        let pk = public_key_decode(&e.pk).expect("decode pk");
        assert!(
            !protocols_verify(&sig, &pk, &e.msg),
            "tampered signature for count {} unexpectedly verified",
            e.count
        );
    }
}

#[test]
fn kat_entries_reject_tampered_message() {
    let path = kat_path();
    let entries = parse_kat(&path);
    let sample: Vec<&KatEntry> = entries.iter().take(5).collect();

    for e in &sample {
        let mut bad_msg = e.msg.clone();
        bad_msg[0] ^= 0x01;
        let sig = signature_decode(&e.sig).expect("decode sig");
        let pk = public_key_decode(&e.pk).expect("decode pk");
        assert!(
            !protocols_verify(&sig, &pk, &bad_msg),
            "tampered message for count {} unexpectedly verified",
            e.count
        );
    }
}
